name: Deploy Resume to Netlify
on:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Prepare Node
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Install Dependencies with yarn
        run: yarn
      - name: Build Gatsby Demo
        run: yarn workspace @josefaidt/resume build
      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.DEMO_NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=resume/.next --prod -m "Deployed with GitHub Actions"
          secrets: '["NETLIFY_AUTH_TOKEN", "DEMO_NETLIFY_SITE_ID"]'